-- 코드를 입력하세요
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) TOTAL_SALES
FROM BOOK A
INNER JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE EXTRACT(YEAR FROM C.SALES_DATE)=2022 AND EXTRACT(MONTH FROM C.SALES_DATE)=1
GROUP BY A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC;