-- 코드를 작성해주세요
SELECT ID
FROM ECOLI_DATA
WHERE ID IN 
(SELECT D.ID
FROM ECOLI_DATA A
INNER JOIN ECOLI_DATA B ON B.PARENT_ID IS NULL AND A.ID = B.ID
INNER JOIN ECOLI_DATA C ON A.ID = C.PARENT_ID
INNER JOIN ECOLI_DATA D ON C.ID = D.PARENT_ID
)
ORDER BY ID