-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100 * 30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR a , CAR_RENTAL_COMPANY_DISCOUNT_PLAN  C
WHERE A.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE TO_CHAR(END_DATE,'YYYYMMDD') >= '20221101')
AND A.CAR_TYPE IN ('세단','SUV')
AND A.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100 * 30 BETWEEN 500000 AND 2000000
AND A.CAR_TYPE = C.CAR_TYPE
AND C.DURATION_TYPE = '30일 이상'
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;