-- 코드를 입력하세요
SELECT A.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM (SELECT FOOD_TYPE FROM REST_INFO GROUP BY FOOD_TYPE) A,
REST_INFO B
WHERE A.FOOD_TYPE = B.FOOD_TYPE
AND (B.FAVORITES, A.FOOD_TYPE) IN (SELECT MAX(FAVORITES), FOOD_TYPE FROM REST_INFO GROUP BY FOOD_TYPE)
ORDER BY A.FOOD_TYPE DESC;