-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, CONCAT(CONCAT(CONCAT(A.CITY,' '), CONCAT(A.STREET_ADDRESS1,' ')), A.STREET_ADDRESS2), CONCAT(CONCAT(CONCAT(SUBSTR(A.TLNO,0,3),'-'),CONCAT(SUBSTR(A.TLNO,4,4),'-')),SUBSTR(A.TLNO,8,4))
FROM USED_GOODS_USER A
WHERE A.USER_ID IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(WRITER_ID) > 2)
ORDER BY A.USER_ID DESC;