-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME,
CONCAT(CONCAT(CONCAT(A.CITY, ' '), CONCAT(A.STREET_ADDRESS1, ' ')), A.STREET_ADDRESS2) AS 전체주소,
CONCAT(CONCAT(CONCAT(SUBSTR(A.TLNO, 0, 3), '-'), CONCAT(SUBSTR(A.TLNO, 4, 4), '-')), SUBSTR(A.TLNO, 8, 4))AS 전화번호
FROM USED_GOODS_USER A
-- INNER JOIN USED_GOODS_BOARD B ON A.USER_ID = B.WRITER_ID
WHERE (A.USER_ID) IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(BOARD_ID) > 2)
ORDER BY A.USER_ID DESC