-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM B.SALES_DATE) AS YEAR, EXTRACT(MONTH FROM B.SALES_DATE) AS MONTH, A.GENDER, COUNT(DISTINCT(B.USER_ID)) AS USERS
FROM USER_INFO A
INNER JOIN ONLINE_SALE B ON B.USER_ID = A.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM B.SALES_DATE), EXTRACT(MONTH FROM B.SALES_DATE), A.GENDER
ORDER BY YEAR, MONTH, A.GENDER;