-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM B.SALES_DATE) YEAR, 
EXTRACT(MONTH FROM B.SALES_DATE) MONTH, 
COUNT(DISTINCT B.USER_ID) PURCHASED_USERS,
ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = 2021) , 1) PUCHASED_RATIO
FROM USER_INFO A
INNER JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID AND EXTRACT(YEAR FROM A.JOINED) = 2021
GROUP BY EXTRACT(YEAR FROM B.SALES_DATE), EXTRACT(MONTH FROM B.SALES_DATE)
ORDER BY YEAR, MONTH