-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM B.SALES_DATE) AS YEAR, EXTRACT(MONTH FROM B.SALES_DATE) AS MONTH, COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = '2021') ,1) AS PUCHASED_RATIO
FROM (SELECT * FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = '2021') A
INNER JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
GROUP BY EXTRACT(YEAR FROM B.SALES_DATE), EXTRACT(MONTH FROM B.SALES_DATE)
ORDER BY EXTRACT(YEAR FROM B.SALES_DATE), EXTRACT(MONTH FROM B.SALES_DATE)
