-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A
INNER JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID AND EXTRACT(YEAR FROM B.PRODUCE_DATE) = 2022 AND EXTRACT(MONTH FROM B.PRODUCE_DATE) = 5
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
ORDER BY SUM(A.PRICE * B.AMOUNT) DESC, A.PRODUCT_ID;