-- 코드를 입력하세요
SELECT B.HISTORY_ID,
CASE
WHEN B.END_DATE - B.START_DATE + 1 >= 90
THEN A.DAILY_FEE * (B.END_DATE - B.START_DATE + 1) * (1 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상') / 100)
WHEN B.END_DATE - B.START_DATE + 1 >= 30
THEN A.DAILY_FEE * (B.END_DATE - B.START_DATE + 1) * (1 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상') / 100)
WHEN B.END_DATE - B.START_DATE + 1 >= 7
THEN A.DAILY_FEE * (B.END_DATE - B.START_DATE + 1) * (1 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상') / 100)
ELSE A.DAILY_FEE * (B.END_DATE - B.START_DATE + 1)
END AS FEE
FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE A.CAR_TYPE = '트럭'
AND A.CAR_ID = B.CAR_ID
ORDER BY FEE DESC, B.HISTORY_ID DESC