-- 코드를 입력하세요
SELECT B.FLAVOR
FROM FIRST_HALF A
INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER1 FROM JULY GROUP BY FLAVOR ORDER BY SUM(TOTAL_ORDER) DESC) B ON A.FLAVOR = B.FLAVOR
ORDER BY B.TOTAL_ORDER1 + A.TOTAL_ORDER DESC
FETCH NEXT 3 ROWS ONLY