-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (SELECT SUM(B.TOTAL_ORDER), A.FLAVOR, A.TOTAL_ORDER FROM FIRST_HALF A, JULY B WHERE A.FLAVOR = B.FLAVOR GROUP BY A.FLAVOR, A.TOTAL_ORDER ORDER BY SUM(B.TOTAL_ORDER) + A.TOTAL_ORDER DESC) A
FETCH NEXT 3 ROWS ONLY;