-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL FROM JULY GROUP BY FLAVOR ORDER BY SUM(TOTAL_ORDER) DESC) A, FIRST_HALF B
WHERE A.FLAVOR = B.FLAVOR
ORDER BY TOTAL + B.TOTAL_ORDER DESC
FETCH NEXT 3 ROWS ONLY;