-- 코드를 입력하세요
-- PATIENT, DOCTOR 그리고 APPOINTMENT 테이블
-- 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역을 조회
SELECT C.APNT_NO, A.PT_NAME, C.PT_NO, C.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM PATIENT A, DOCTOR B
INNER JOIN APPOINTMENT C ON B.DR_ID = C.MDDR_ID
WHERE C.MCDP_CD = 'CS' AND C.APNT_CNCL_YN = 'N' AND A.PT_NO = C.PT_NO AND B.MCDP_CD = 'CS' AND B.DR_ID = C.MDDR_ID AND TO_CHAR(C.APNT_YMD,'YYYYMMDD') = '20220413'
ORDER BY C.APNT_YMD;