-- 코드를 입력하세요
SELECT A.HOUR, NVL(COUNT(B.ANIMAL_ID), 0) AS COUNT
FROM (SELECT LEVEL - 1 AS HOUR FROM DUAL CONNECT BY LEVEL < 25) A
LEFT JOIN ANIMAL_OUTS B ON A.HOUR = TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
GROUP BY A.HOUR
ORDER BY A.HOUR