-- 코드를 입력하세요
SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR, COUNT(EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))) AS COUNT
FROM ANIMAL_OUTS
GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
HAVING EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) > 8 AND
EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) < 20
ORDER BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP));