-- 코드를 입력하세요
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, TO_CHAR(B.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE A
INNER JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(MEMBER_ID) DESC FETCH FIRST 1 ROW ONLY)
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT
-- SELECT MEMBER_ID
-- FROM REST_REVIEW
-- GROUP BY MEMBER_ID
-- ORDER BY COUNT(MEMBER_ID) DESC
-- FETCH FIRST 1 ROW ONLY