-- 코드를 입력하세요
SELECT A.MEMBER_NAME, C.REVIEW_TEXT, TO_CHAR(C.REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE 
FROM MEMBER_PROFILE A, (SELECT MEMBER_ID, COUNT(MEMBER_ID) AS CNT 
                        FROM REST_REVIEW
                        GROUP BY MEMBER_ID
                        ORDER BY COUNT(MEMBER_ID) DESC
                        FETCH FIRST 1 ROW ONLY) B, REST_REVIEW C
WHERE A.MEMBER_ID = B.MEMBER_ID AND C.MEMBER_ID = B.MEMBER_ID
ORDER BY C.REVIEW_DATE, C.REVIEW_TEXT;
