-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID 
IN (
SELECT CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE TO_CHAR(START_DATE,'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
GROUP BY CAR_ID 
HAVING COUNT(CAR_ID) >= 5)

AND TO_CHAR(START_DATE,'YYYY-MM') BETWEEN '2022-08' AND '2022-10' 
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY EXTRACT(MONTH FROM START_DATE), CAR_ID DESC;