-- 코드를 작성해주세요
-- SQLINES LICENSE FOR EVALUATION USE ONLY
SELECT COUNT(*) AS FISH_COUNT, MONTH(DATE_FORMAT(TIME, '%Y-%m-%d')) AS MONTH FROM FISH_INFO GROUP BY MONTH(DATE_FORMAT(TIME, '%Y-%m-%d')) ORDER BY MONTH(DATE_FORMAT(TIME, '%Y-%m-%d')) ASC;