-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
INNER JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE (A.LENGTH, A.FISH_TYPE) IN (SELECT MAX(IFNULL(LENGTH, 10)), FISH_TYPE FROM FISH_INFO WHERE A.FISH_TYPE = FISH_TYPE GROUP BY FISH_TYPE)
ORDER BY ID