-- 코드를 작성해주세요
SELECT SUM(C.SCORE) AS SCORE, C.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL 
FROM HR_DEPARTMENT A, HR_EMPLOYEES B, HR_GRADE C
WHERE C.EMP_NO = B.EMP_NO AND A.DEPT_ID = B.DEPT_ID AND C.YEAR = 2022
GROUP BY C.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL 
ORDER BY SUM(C.SCORE) DESC
LIMIT 1;
