-- 코드를 입력하세요
SELECT CONCAT(CONCAT(CONCAT('/home/grep/src/',B.BOARD_ID), CONCAT('/',B.FILE_ID)),CONCAT(B.FILE_NAME, B.FILE_EXT)) AS FILE_PATH
FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_FILE B ON A.BOARD_ID = B.BOARD_ID
WHERE A.VIEWS IN (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD FETCH FIRST 1 ROWS ONLY)
ORDER BY FILE_PATH DESC