-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.SALES)
FROM BOOK A
INNER JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
AND EXTRACT(YEAR FROM B.SALES_DATE) = '2022' AND EXTRACT(MONTH FROM B.SALES_DATE) = '1'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY;